# Generated by Django 4.2.2 on 2023-06-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('code_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.code')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book',
            },
            bases=('product.code',),
        ),
    ]
