# Generated by Django 4.2.2 on 2023-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_code_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avaialableDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='avaialbleDttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='avaialbletime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
